import {
    addComponentsDir,
    addPlugin,
    addTypeTemplate,
    createResolver,
    defineNuxtModule,
    resolvePath
} from '@nuxt/kit';

// Module options TypeScript interface definition
export interface ModuleOptions {}

export default defineNuxtModule<ModuleOptions>({
    meta: {
        name: '@cyrilverloop/nuxt-bootstrap',
        configKey: 'nuxtBootstrap',
    },
    // Default configuration options of the Nuxt module
    defaults: {},
    async setup(_options, _nuxt) {
        _nuxt.options.css.push('bootstrap/dist/css/bootstrap.min.css');
        const { resolve } = createResolver(import.meta.url);

        // Do not add the extension since the `.ts` will be transpiled to `.mjs` after `npm run prepack`
        addPlugin(resolve('./runtime/plugins/useBootstrap.client'));

        addComponentsDir({
            path: resolve('./runtime/components/')
        });

        addTypeTemplate({
            filename: 'types/nuxt-bootstrap.d.ts',
            getContents: () => `// Generated by nuxt-bootstrap\n`
            + `import { type BSAccordionItem } from "` + resolve('./runtime/types/BSAccordionItem.d') + `";\n`
            + `import { type BSBadge } from "` + resolve('./runtime/types/BSBadge.d') + `";\n`
            + `import { type BSBreadcrumb } from "` + resolve('./runtime/types/BSBreadcrumb.d') + `";\n`
            + `import { type BSBreadcrumbs } from "` + resolve('./runtime/types/BSBreadcrumbs.d') + `";\n`
            + `import { type BSIconPageItem } from "` + resolve('./runtime/types/BSIconPageItem.d') + `";\n`
            + `import { type BSNavItem } from "` + resolve('./runtime/types/BSNavItem.d') + `";\n`
            + `import { type BSPageItem } from "` + resolve('./runtime/types/BSPageItem.d') + `";\n`
            + `import { type BSProgress } from "` + resolve('./runtime/types/BSProgress.d') + `";\n`
            + `import { BSAutoClose } from "` + resolve('./runtime/types/BSAutoClose') + `";\n`
            + `import { BSDropdownContent } from "` + resolve('./runtime/types/dropdown/BSDropdownContent') + `";\n`
            + `import { BSDropdownDirection } from "` + resolve('./runtime/types/dropdown/BSDropdownDirection') + `";\n`
            + `import { BSDropdownDivider } from "` + resolve('./runtime/types/dropdown/BSDropdownDivider') + `";\n`
            + `import { BSDropdownLink } from "` + resolve('./runtime/types/dropdown/BSDropdownLink') + `";\n`
            + `import { BSDropdownText } from "` + resolve('./runtime/types/dropdown/BSDropdownText') + `";\n`
            + `import { BSDropdownTitle } from "` + resolve('./runtime/types/dropdown/BSDropdownTitle') + `";\n`
            + `import { BSJustifyContent } from "` + resolve('./runtime/types/BSJustifyContent') + `";\n`
            + `import { BSSize } from "` + resolve('./runtime/types/BSSize') + `";\n`
            + `import { BSSpinnerType } from "` + resolve('./runtime/types/BSSpinnerType') + `";\n`
            + `import BSVariant from "` + resolve('./runtime/types/BSVariant') + `";\n`
            + `export {`
            + `type BSAccordionItem,`
            + `type BSBadge,`
            + `type BSBreadcrumb,`
            + `type BSBreadcrumbs,`
            + `type BSIconPageItem,`
            + `type BSNavItem,`
            + `type BSProgress,`
            + `type BSPageItem,`
            + `BSAutoClose,`
            + `BSDropdownContent,`
            + `BSDropdownDirection,`
            + `BSDropdownDivider,`
            + `BSDropdownLink,`
            + `BSDropdownText,`
            + `BSDropdownTitle,`
            + `BSJustifyContent,`
            + `BSSize,`
            + `BSSpinnerType,`
            + `BSVariant`
            + `};`,
        });

        _nuxt.options.alias['#nbs'] = await resolvePath("#build") + "/types/nuxt-bootstrap.d";
    }
});
