import {
    addComponentsDir,
    addPlugin,
    addTypeTemplate,
    createResolver,
    defineNuxtModule
} from '@nuxt/kit';

// Module options TypeScript interface definition
export interface ModuleOptions {}

export default defineNuxtModule<ModuleOptions>({
    meta: {
        name: '@cyrilverloop/nuxt-bootstrap',
        configKey: 'nuxtBootstrap',
    },
    // Default configuration options of the Nuxt module
    defaults: {},
    setup(_options, _nuxt) {
        _nuxt.options.css.push('bootstrap/dist/css/bootstrap.min.css');
        const resolver = createResolver(import.meta.url);

        // Do not add the extension since the `.ts` will be transpiled to `.mjs` after `npm run prepack`
        addPlugin(resolver.resolve('./runtime/plugins/useBootstrap.client'));

        addComponentsDir({
            path: resolver.resolve('./runtime/components/')
        });

        addTypeTemplate({
            filename: 'types/nuxt-bootstrap.d.ts',
            getContents: () => `// Generated by nuxt-bootstrap\n`
            + `import { type BSBadge } from "` + resolver.resolve('./runtime/types/BSBadge') + `";\n`
            + `import { BSVariant } from "` + resolver.resolve('./runtime/types/BSVariant') + `";\n`
            + `export {`
            + `type BSBadge,`
            + `BSVariant`
            + `};`,
        });

        const typesFile = resolver.resolve('./../.nuxt/types/nuxt-bootstrap.d');
        _nuxt.options.alias['#nbs'] = typesFile;
    }
});
